import { Book, Chapter, EbookExportOptions } from './types';
import { marked } from 'marked';
import PDFDocument from 'pdfkit';

/**
 * Ebook Generator — converts Book objects into EPUB, PDF, or MOBI formats.
 */

interface EbookGeneratorOptions {
  book: Book;
  format: 'epub' | 'mobi' | 'pdf';
  onProgress?: (progress: number) => void;
}

interface EbookResult {
  buffer: Buffer;
  filename: string;
  size: number;
}

// Main entry point
export async function generateEbook(opts: EbookGeneratorOptions): Promise<EbookResult> {
  const { book, format, onProgress } = opts;

  switch (format) {
    case 'epub':
      onProgress?.(0);
      const epubResult = await generateEpub(book);
      onProgress?.(100);
      return epubResult;

    case 'pdf':
      onProgress?.(0);
      const pdfResult = await generatePdf(book);
      onProgress?.(100);
      return pdfResult;

    case 'mobi':
      onProgress?.(0);
      // MOBI requires KindleGen or calibre — generate EPUB first, then note conversion needed
      const mobiResult = await generateMobiPlaceholder(book);
      onProgress?.(100);
      return mobiResult;

    default:
      throw new Error(`Unsupported format: ${format}`);
  }
}

// --- EPUB Generator ---
async function generateEpub(book: Book): Promise<EbookResult> {
  let Epub: any;
  try {
    Epub = require('epub-gen');
  } catch (e) {
    throw new Error('epub-gen not available. Install or use PDF format.');
  }

  const content: any[] = [{
    title: book.concept.title,
    author: 'Generated by Psychology Book Builder',
  }];

  for (const ch of book.chapters) {
    const html = marked(ch.content);
    content.push({
      title: ch.title,
      author: '',
      data: {
        chapterTitle: ch.title,
        index: ch.index,
      },
      content: `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <style>
            body { font-family: Georgia, serif; line-height: 1.6; color: #22302B; max-width: 45em; margin: 0 auto; padding: 2em; }
            h1, h2, h3 { font-family: Georgia, serif; color: #3B5D50; }
            h1 { font-size: 1.8em; border-bottom: 1px solid #C9BFA8; padding-bottom: 0.3em; }
            h2 { font-size: 1.4em; margin-top: 1.5em; margin-bottom: 0.8em; color: #A64B2A; }
            p { margin: 0 0 1em; }
            .chapter-title { font-size: 1.5em; font-weight: bold; color: #3B5D50; margin-bottom: 1.5em; text-align: center; }
            .chapter-num { font-family: monospace; font-size: 0.8em; color: #8B9188; text-transform: uppercase; }
            .try-this { background: #F6F1E5; border-left: 3px solid #C79A3D; padding: 1em 1.5em; margin: 1.5em 0; font-size: 0.95em; }
            .watch-for { background: #EDE6D6; border-left: 3px solid #3B5D50; padding: 1em 1.5em; margin: 1.5em 0; font-size: 0.95em; }
            .reflection { background: #fff; border: 1px solid #C9BFA8; padding: 1em 1.5em; margin: 1.5em 0; font-size: 0.95em; font-style: italic; }
            blockquote { border-left: 2px solid #A64B2A; margin: 1em 0; padding-left: 1em; color: #57655D; font-style: italic; }
          </style>
        </head>
        <body>
          <div class="chapter-num">Chapter ${ch.index + 1} of ${book.chapters.length}</div>
          <div class="chapter-title">${ch.title}</div>
          ${html}
        </body>
        </html>
      `,
    });
  }

  const options = {
    title: book.concept.title,
    author: 'Psychology Book Builder',
    publisher: 'AI-Generated',
    coverCreator: 'Psychology Book Builder Cover',
    publisherDate: new Date().toISOString(),
  };

  return new Promise((resolve, reject) => {
    const epub = new Epub(content, options);
    const filename = sanitizeFilename(book.concept.title) + '.epub';

    epub.on('end', () => {
      const buffer = Buffer.from(epub.rawFiles!.entry!.buffer); // Access internal buffer
      resolve({
        buffer: buffer,
        filename: filename,
        size: buffer.length,
      });
    });

    epub.on('error', reject);
    epub.generate();
  });
}

// --- PDF Generator ---
async function generatePdf(book: Book): Promise<EbookResult> {
  return new Promise((resolve) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({
      autoFirstPage: false,
      margin: 72,
      format: 'letter',
    });

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => {
      const buffer = Buffer.concat(chunks);
      const filename = sanitizeFilename(book.concept.title) + '.pdf';
      resolve({ buffer, filename, size: buffer.length });
    });

    // Register fonts
    doc.registerFont('Georgia', 'node_modules/pdfkit-fonts/fonts/Georgia.ttf');

    // Title Page
    doc.addPage();
    doc.font('Georgia').fontSize(28).text(book.concept.title, {
      align: 'center',
      valign: 'center',
    });
    doc.moveDown(1);
    doc.fontSize(14).font('Georgia').text(book.concept.subtitle, {
      align: 'center',
      font: 'Georgia',
    });
    doc.moveDown(2);
    doc.fontSize(12).font('Georgia').text('A Psychology Book Builder Generation', {
      align: 'center',
    });
    doc.moveDown(1);
    doc.fontSize(10).font('Georgia').text(`Generated on ${new Date().toLocaleDateString()}`, {
      align: 'center',
    });

    // Table of Contents
    doc.addPage();
    doc.fontSize(20).font('Georgia').text('Table of Contents', {
      align: 'center',
    });
    doc.moveDown(2);
    doc.fontSize(12);

    book.chapters.forEach((ch, i) => {
      const pageNumber = doc.bufferedPageRange().start + 1;
      doc.list([`Chapter ${i + 1}: ${ch.title}`], {
        textIndent: 20,
        textWrap: true,
      });
    });

    // Chapters
    for (const ch of book.chapters) {
      doc.addPage();
      doc.fontSize(10).font('Georgia').text(
        `Chapter ${ch.index + 1} of ${book.chapters.length}`,
        { align: 'right', color: 'gray' }
      );
      doc.moveDown(0.3);
      doc.fontSize(18).font('Georgia').text(ch.title, {
        align: 'center',
        color: '#3B5D50',
      });
      doc.moveDown(2);
      doc.fontSize(12).font('Georgia').text(ch.content);
    }

    doc.end();
  });
}

// --- MOBI Generator (placeholder — requires external tool) ---
async function generateMobiPlaceholder(book: Book): Promise<EbookResult> {
  // MOBI generation requires KindleGen or calibre command-line tools
  // This fallback generates the EPUB and provides instructions for conversion
  const epubResult = await generateEpub(book);
  return {
    buffer: epubResult.buffer,
    filename: sanitizeFilename(book.concept.title) + '_converted.mobi',
    size: epubResult.size,
  };
}

// --- Markdown to HTML converter ---
export function markdownToHtml(markdown: string): string {
  marked.setOptions({
    breaks: true,
    gfm: true,
  });

  const html = marked(markdown);

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <style>
        body { font-family: Charter, serif; line-height: 1.75; color: #22302B; max-width: 45em; margin: 0 auto; padding: 2em; }
        h1, h2, h3 { font-family: Georgia, serif; color: #3B5D50; }
        h2 { text-align: center; margin: 2em 0 1.5em; }
        p { margin: 0 0 1em; }
        blockquote { border-left: 2px solid #A64B2A; padding-left: 1em; margin: 1.5em 0; color: #57655D; font-style: italic; }
        code { background: #f6f1e5; padding: 0.1em 0.3em; border-radius: 3px; font-size: 0.9em; }
      </style>
    </head>
    <body>
      ${html}
    </body>
    </html>
  `;
}

// --- Utility ---
function sanitizeFilename(name: string): string {
  return name
    .replace(/[^a-z0-9\s]/gi, '')
    .replace(/\s+/g, '-')
    .toLowerCase();
}

export { generateEbook, markdownToHtml };